djangoProject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>/', views.add_cart, name='add_cart'),
    path('remove/<int:id>/', views.remove_cart, name='remove_cart'),
    path('add_single/<int:id>/', views.add_single, name='add_single'),
    path('remove_single/<int:id>/', views.remove_single, name='remove_single'),
    path('compare/<int:id>/', views.compare, name='compare'),
    path('show/', views.show, name='show'),
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.sitemaps import ProductViewSitemaps
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'product': ProductViewSitemaps,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('account.urls', namespace='account')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('sitemaps.xml/', sitemap, {'sitemaps': sitemaps}),

]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('<int:order_id>/', views.order_detail, name='order_detail'),
    path('create/', views.order_create, name='order_create'),
    path('coupon/<int:order_id>/', views.coupon_order, name='coupon'),
    path('request/<int:order_id>/<int:price>/', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
]

djangoProject/cart/models.py
from django.db import models
from home.models import *
from django.forms import ModelForm


# Create your models here.


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class CartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['quantity']


class Compare(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,)
    session_key = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return self.product.name


class CompareForm(ModelForm):
    class Meta:
        model = Compare
        fields = ['product']

djangoProject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from home.models import Product
from .models import *
from django.contrib.auth.decorators import login_required
from order.models import *
from django.contrib import messages
# Create your views here.


def cart_detail(request):
    cart = Cart.objects.filter(user_id=request.user.id)
    user = request.user
    form = OrderForm()
    total = 0
    for p in cart:
        if p.product.status != 'None':
            total += p.variant.total_price * p.quantity
        else:
            total += p.product.total_price * p.quantity
    return render(request, 'cart/cart.html', {'cart': cart, 'total': total, 'form': form, 'user': user})


@login_required(login_url='account:user_login')
def add_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    if product.status != 'None':
        var_id = request.POST.get('select')
        data = Cart.objects.filter(user_id=request.user.id, variant_id=var_id)
        if data:
            check = 'yes'
        else:
            check = 'no'
    else:
        data = Cart.objects.filter(user_id=request.user.id, product_id=id)
        if data:
            check = 'yes'
        else:
            check = 'no'

    if request.method == 'POST':
        form = CartForm(request.POST)
        var_id = request.POST.get('select')
        if form.is_valid():
            info = form.cleaned_data['quantity']
            if check == 'yes':
                if product.status != 'None':
                    shop = Cart.objects.get(user_id=request.user.id, product_id=id, variant_id=var_id)
                else:
                    shop = Cart.objects.get(user_id=request.user.id, product_id=id)
                shop.quantity += info
                shop.save()
            else:
                Cart.objects.create(user_id=request.user.id, product_id=id, variant_id=var_id, quantity=info)

    return redirect(url)


@login_required(login_url='account:user_login')
def remove_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    Cart.objects.filter(id=id).delete()
    return redirect(url)


def add_single(request, id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart.objects.get(id=id)
    if cart.product.status == 'None':
        product = Product.objects.get(id=cart.product.id)
        if product.amount > cart.quantity:
            cart.quantity += 1
    else:
        variant = Variants.objects.get(id=cart.variant.id)
        if variant.amount > cart.quantity:
            cart.quantity += 1
    cart.save()
    return redirect(url)


def remove_single(request, id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart.objects.get(id=id)
    if cart.quantity < 2:
        cart.delete()
    else:
        cart.quantity -= 1
        cart.save()
    return redirect(url)


def compare(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.user.is_authenticated:
        item = get_object_or_404(Product, id=id)
        qs = Compare.objects.filter(user_id=request.user.id, product_id=id)
        if qs.exists():
            messages.success(request, 'ok user')
        else:
            Compare.objects.create(user_id=request.user.id, product_id=item.id, session_key=None)
    else:
        item = get_object_or_404(Product, id=id)
        qs = Compare.objects.filter(user_id=None, product_id=id, session_key=request.session.session_key)
        if qs.exists():
            messages.success(request, 'ok session')
        else:
            if not request.session.session_key:
                request.session.create()
            Compare.objects.create(user_id=None, product_id=item.id, session_key=request.session.session_key)
    return redirect(url)


def show(request):
    if request.user.is_authenticated:
        data = Compare.objects.filter(user_id=request.user.id)
        return render(request, 'cart/show.html', {'data': data})
    else:
        data = Compare.objects.filter(session_key__exact=request.session.session_key, user_id=None)
        return render(request, 'cart/show.html', {'data': data})

djangoProject/cart/templates/cart/cart.html
{% extends 'base.html' %}
{% block title %}
    cart
{% endblock %}
{% block moha %}
<h1>cart</h1>
    <div class="container">
    <div class="row">
    <table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">image</th>
      <th scope="col">product</th>
      <th scope="col">size</th>
      <th scope="col">color</th>
      <th scope="col">price</th>
      <th scope="col">quantity</th>
      <th scope="col">total price</th>
      <th scope="col">remove</th>
    </tr>
  </thead>
  <tbody>

  {% for c in cart %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><img src="{{ c.product.image.url }}" style="width: 70px" alt=""></td>
      <td>{{ c.product.name }}</td>
      <td>{{ c.variant.size_variant.name }}</td>
      <td>{{ c.variant.color_variant.name }}</td>
    <td>
        {% if c.product.status != 'None' %}
        {{ c.variant.total_price }}
         {% else %}
            {{ c.product.total_price }}
        {% endif %}
    </td>
    <td>
        <a href="{% url 'cart:add_single' c.id %}"><i class="fa fa-plus"></i></a>
        {{ c.quantity }}
        <a href="{% url 'cart:remove_single' c.id %}"><i class="fa fa-minus"></i></a>

    </td>
    <td>
        {% if c.product.status != 'None' %}
        {% widthratio c.variant.total_price 1 c.quantity %}
        {% else %}
            {% widthratio c.product.total_price 1 c.quantity %}
        {{ c.product.total_price }}
        {% endif %}
    </td>
    <td>
        <a href="{% url 'cart:remove_cart' c.id %}"><i class="fa fa-trash" style="color: red"></i></a>
    </td>
    </tr>
  {% endfor %}
  <tr>
      <td colspan="7">total</td>
      <td> {{ total }}</td>
  </tr>


  </tbody>
</table>
    </div>


    <div class="row">
        <form method="post" action="{% url 'order:order_create' %}">
        {% csrf_token %}
        <div class="card" style="padding: 10px; background-color: #ad9f9f">
            <label for="">email:
            <input type="email" name="email" value="{{ user.email }}">
            </label>
             <label for="">name:
            <input type="text" name="first_name" value="{{ user.first_name }}">
            </label>
             <label for="">last_name:
            <input type="text" name="last_name" value="{{ user.last_name }}">
            </label>
             <label for="">address:
            <input type="text" name="address" value="{{ user.profile.address }}">
            </label>
        </div>
        <br>
        <button type="submit" class="btn btn-outline-danger">order</button>
    </form>
    </div>
    </div>
{% endblock %}

djangoProject/cart/templates/cart/show.html
{% extends 'base.html' %}
{% block moha %}
<div class="container">
{% for i in data %}
    <h2>{{ i.product.name }}</h2><br>
{% endfor %}
</div>
{% endblock %}