djangoProject/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('logout', views.log_out, name='log_out'),
    path('login/', views.user_login, name='user_login'),
    path('profile/', views.user_profile, name='user_profile'),
    path('update/', views.user_update, name='user_update'),
    path('change/', views.change_password, name='change_password'),
    path('login_phone/', views.phone, name='phone'),
    path('verify/', views.verify, name='verify'),
    path('active/<uidb64>/<token>/', views.RegisterEmail.as_view(), name='active'),
    path('reset', views.ResetPassword.as_view(), name='reset'),
    path('reset/done', views.DonePassword.as_view(), name='reset_done'),
    path('confirm/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='password_reset_confirm'),
    path('confirm/done/', views.Complete.as_view(), name='complete'),
    path('favourite/', views.favourite, name='favourite'),
    path('history/', views.history, name='history'),
    path('view/', views.product_view, name='product_view'),
]

djangoProject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>/', views.add_cart, name='add_cart'),
    path('remove/<int:id>/', views.remove_cart, name='remove_cart'),
    path('add_single/<int:id>/', views.add_single, name='add_single'),
    path('remove_single/<int:id>/', views.remove_single, name='remove_single'),
    path('compare/<int:id>/', views.compare, name='compare'),
    path('show/', views.show, name='show'),
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.sitemaps import ProductViewSitemaps
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'product': ProductViewSitemaps,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('account.urls', namespace='account')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('sitemaps.xml/', sitemap, {'sitemaps': sitemaps}),

]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('product', views.all_product, name='product'),
    path('detail/<int:id>', views.product_detail, name='detail'),
    path('category/<slug>/<int:id>/', views.all_product, name='category'),
    path('like/<int:id>/', views.product_like, name='product_like'),
    path('dislike/<int:id>/', views.product_dislike, name='product_dislike'),
    path('dislike/<int:id>/', views.product_dislike, name='product_dislike'),
    path('comment/<int:id>/', views.product_comment, name='product_comment'),
    path('reply/<int:id>/<int:comment_id>/', views.product_reply, name='product_reply'),
    path('like_comment/<int:id>/', views.comment_like, name='comment_like'),
    path('dislike_comment/<int:id>/', views.comment_dislike, name='comment_dislike'),
    path('search/', views.product_search, name='product_search'),
    path('favourite/<int:id>', views.favourite_product, name='favourite'),
    path('contact/', views.contact, name='contact'),
]

djangoProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
<!-- CSS only -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{% block css %}{% endblock %}
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<link rel='stylesheet' href='https://sachinchoolur.github.io/lightslider/dist/css/lightslider.css'>

</head>
<body>

{% include 'navbar.html' %}
{% include 'message.html' %}
{% block moha %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
{% block script %}{% endblock %}

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
</body>
</html>

djangoProject/templates/message.html
{% if messages %}
{% for msg in messages %}
    <h3
    class="alert alert-warning"
    >{{ msg }}</h3>

    {% endfor %}
{% endif %}

djangoProject/templates/navbar.html
{% load static  %}
<link rel="stylesheet" href="{% static 'bass/css/nav.css' %}">
<div class="nav">
    <div class="container">
         <ul>
        <li><a href="{% url 'home:home' %}">Home</a></li>
      <li>
          <a href="{% url 'home:product' %}">Product</a>
        </li>

          {% if user.is_authenticated %}


              <li>Category
              <ul>
                  {% for cat in category  %}
                  <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                  <ul>
                      {% for data in cat.sub.all %}
                      <li><a href="{{ data.get_absolute_url }}">{{ data.name }}</a>
                      <ul>
                          {% for i in data.sub.all %}
                          <li><a href="{{ i.get_absolute_url }}">{{ i.name }}</a>

                          </li>
                              {% endfor %}
                      </ul>
                      </li>
                          {% endfor %}
                  </ul>

                  </li>
                  {% endfor %}
              </ul>
              </li>
              <li>
          <a href="{% url 'cart:cart_detail' %}">Cart {{ nums }}</a>
        </li>
              <li>
          <a href="{% url 'account:user_profile' %}">Profile</a>
        </li>
                   <li>
          <a href="{% url 'home:contact' %}">Contact</a>
        </li>
                  <li>
          <a href="{% url 'account:log_out' %}">Logout</a>
        </li>
          {% else %}
        <li>
          <a href="{% url 'account:user_login' %}">Login</a>
        </li>
          <li>
          <a href="{% url 'account:user_register' %}">Register</a>
        </li>

              {% if not user.is_authenticated %}
                  <li >
          <a href="{% url 'account:phone' %}">Login Phone</a>
        </li>

              {% endif %}
        {% endif %}

      </ul>
    <form class="form-inline float-sm-right" action="{% url 'home:product' %}">
        <input class="form-control" type="search" placeholder="Search" name="search">
        <input type="submit" value="search" class="btn btn-danger">

    </form>

    </div>
</div>