djangoProject/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:id>/', views.add_cart, name='add_cart'),
    path('remove/<int:id>/', views.remove_cart, name='remove_cart'),
    path('add_single/<int:id>/', views.add_single, name='add_single'),
    path('remove_single/<int:id>/', views.remove_single, name='remove_single'),
    path('compare/<int:id>/', views.compare, name='compare'),
    path('show/', views.show, name='show'),
]

djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home.sitemaps import ProductViewSitemaps
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'product': ProductViewSitemaps,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('account.urls', namespace='account')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('sitemaps.xml/', sitemap, {'sitemaps': sitemaps}),

]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('product', views.all_product, name='product'),
    path('detail/<int:id>', views.product_detail, name='detail'),
    path('category/<slug>/<int:id>/', views.all_product, name='category'),
    path('like/<int:id>/', views.product_like, name='product_like'),
    path('dislike/<int:id>/', views.product_dislike, name='product_dislike'),
    path('dislike/<int:id>/', views.product_dislike, name='product_dislike'),
    path('comment/<int:id>/', views.product_comment, name='product_comment'),
    path('reply/<int:id>/<int:comment_id>/', views.product_reply, name='product_reply'),
    path('like_comment/<int:id>/', views.comment_like, name='comment_like'),
    path('dislike_comment/<int:id>/', views.comment_dislike, name='comment_dislike'),
    path('search/', views.product_search, name='product_search'),
    path('favourite/<int:id>', views.favourite_product, name='favourite'),
    path('contact/', views.contact, name='contact'),
]

djangoProject/home/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)

djangoProject/home/views.py
import requests
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib import messages
from .forms import *
from django.db.models import Q, Max, Min, Count, Sum
from cart.models import *
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from .filters import ProductFilter
from urllib.parse import urlencode


# Create your views here.


def home(request):
    category = Category.objects.filter(sub_cat=False)
    gallery = Gallery.objects.all()
    create = Product.objects.all().order_by('-create')[:4]
    nums = Cart.objects.filter(user_id=request.user.id).aggregate(sum=Sum('quantity'))['sum']
    return render(request, 'home/home.html', {'category': category, 'gallery': gallery, 'create': create, 'nums': nums})


def all_product(request, slug=None, id=None):
    products = Product.objects.all()
    form = CompareForm()
    comment_form = CommentForm()
    min = Product.objects.aggregate(unit_price=Min('unit_price'))
    min_price = int(min['unit_price'])
    max = Product.objects.aggregate(unit_price=Max('unit_price'))
    max_price = int(max['unit_price'])
    filter = ProductFilter(request.GET, queryset=products)
    products = filter.qs
    paginator = Paginator(products, 3)
    page_num = request.GET.get('page')

    page_obj = paginator.get_page(page_num)
    category = Category.objects.filter(sub_cat=False)
    if slug and id:
        data = get_object_or_404(Category, slug=slug, id=id)
        page_obj = products.filter(category=data)
        paginator = Paginator(page_obj, 3)
        page_num = request.GET.get('page')
        # data = request.GET.copy()
        # if 'page' in data:
        #     del data['page']
        page_obj = paginator.get_page(page_num)
    s_form = SearchForm()
    if 'search' in request.GET:
        s_form = SearchForm(request.GET)
        if s_form.is_valid():
            info = s_form.cleaned_data['search']
            page_obj = products.filter(Q(name__icontains=info))
            paginator = Paginator(page_obj, 3)
            page_num = request.GET.get('page')
            # data = request.GET.copy()
            # if 'page' in data:
            #     del data['page']
            page_obj = paginator.get_page(page_num)
    return render(request, "home/product.html",
                  {'products': page_obj, 's_form': s_form, 'page_num': page_num, 'filter': filter,
                   'min_price': min_price, 'max_price': max_price, 'category': category,
                   'form': form, 'comment_form': comment_form})


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    # product.num_view += 1
    # product.save()
    ip = request.META.get('REMOTE_ADDR')
    view = Views.objects.filter(product_id=product.id, ip=ip)
    if not view.exists():
        Views.objects.create(product_id=product.id, ip=ip)
        product.num_view += 1
        product.save()
    if request.user.is_authenticated:
        product.view.add(request.user)
    update = Chart.objects.filter(product_id=id)
    change = Chart.objects.all()
    images = Images.objects.filter(product_id=id)
    comment_form = CommentForm()
    reply_form = ReplyForm()
    cart_form = CartForm()
    comment = Comment.objects.filter(product_id=id, is_reply=False)
    similar = product.tags.similar_objects()[:2]
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        is_like = True
    is_dislike = False
    if product.dislike.filter(id=request.user.id).exists():
        is_dislike = True
    is_favourite = False
    if product.favourite.filter(id=request.user.id).exists():
        is_favourite = True
    if product.status != 'None':
        if request.method == 'POST':
            variant = Variants.objects.filter(product_variant_id=id)
            var_id = request.POST.get('select')
            variants = Variants.objects.get(id=var_id)
            colors = Variants.objects.filter(product_variant_id=id, size_variant=variants.size_variant_id)
            size = Variants.objects.raw(
                'SELECT * FROM home_variants WHERE product_variant_id=%s GROUP BY size_variant_id', [id])
        else:
            variant = Variants.objects.filter(product_variant_id=id)
            variants = Variants.objects.get(id=variant[0].id)
            colors = Variants.objects.filter(product_variant_id=id, size_variant=variants.size_variant_id)
            size = Variants.objects.raw(
                'SELECT * FROM home_variants WHERE product_variant_id=%s GROUP BY size_variant_id', [id])
            # برای اسکولایت از بالایی و برای پستگرس از پایینی استفاده میکنیم
            # sizes = Variants.objects.filter(product_variant_id=id).distinct('size_variant_id')
        context = {'product': product, 'variant': variant,
                   'variants': variants, 'similar': similar,
                   'is_like': is_like, 'is_dislike': is_dislike,
                   'comment_form': comment_form, 'comment': comment,
                   'reply_form': reply_form, 'images': images, 'cart_form': cart_form, 'is_favourite': is_favourite,
                   'change': change, 'colors': colors, 'size': size}
        return render(request, 'home/detail.html', context)
    else:
        return render(request, 'home/detail.html',
                      {'product': product, 'similar': similar,
                       'is_like': is_like, 'is_dislike': is_dislike,
                       'comment_form': comment_form, 'comment': comment,
                       'reply_form': reply_form, 'images': images, 'cart_form': cart_form,
                       'is_favourite': is_favourite, 'update': update})


def product_like(request, id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product, id=id)
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
        is_like = False
        messages.success(request, 'remove', 'success')
    else:
        product.like.add(request.user)
        is_like = True
        messages.success(request, 'add', 'warning')
    return redirect(url)


def product_dislike(request, id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    if product.dislike.filter(id=request.user.id).exists():
        product.dislike.remove(request.user)
    else:
        product.dislike.add(request.user)
    return redirect(url)


def product_comment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            data = comment_form.cleaned_data
            Comment.objects.create(comment=data['comment'], rate=data['rate'], user_id=request.user.id, product_id=id)
            # messages.success(request, 'tnx for comment')
        return redirect(url)


def product_reply(request, id, comment_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        reply_form = ReplyForm(request.POST)
        if reply_form.is_valid():
            data = reply_form.cleaned_data
            Comment.objects.create(comment=data['comment'], product_id=id, user_id=request.user.id, reply_id=comment_id,
                                   is_reply=True)
            messages.success(request, 'tnx for reply')
            return redirect(url)


def comment_like(request, id):
    url = request.META.get('HTTP_REFERER')
    comment = Comment.objects.get(id=id)
    if comment.comment_like.filter(id=request.user.id).exists():
        comment.comment_like.remove(request.user)
    else:
        comment.comment_like.add(request.user)

    return redirect(url)


def comment_dislike(request, id):
    url = request.META.get('HTTP_REFERER')
    comment = Comment.objects.get(id=id)
    if comment.comment_dislike.filter(id=request.user.id).exists():
        comment.comment_dislike.remove(request.user)
    else:
        comment.comment_dislike.add(request.user)
    return redirect(url)


def product_search(request):
    products = Product.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']
            if data.isdigit():
                products = products.filter(Q(discount__exact=data) | Q(unit_price__exact=data))
            else:
                products = products.filter(Q(name__icontains=data))
            return render(request, 'home/product.html', {'products': products, 'form': form})


def favourite_product(request, id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=id)
    is_favourite = False
    if product.favourite.filter(id=request.user.id).exists():
        product.favourite.remove(request.user)
        product.total_favourite -= 1
        product.save()
        is_favourite = False
    else:
        product.favourite.add(request.user)
        product.total_favourite += 1
        product.save()
        is_favourite = True
    return redirect(url)


def contact(request):
    if request.method == 'POST':
        subject = request.POST['subject']
        email = request.POST['email']
        msg = request.POST['message']
        body = subject + '\n' + email + '\n' + msg
        form = EmailMessage(
            'contact form',
            body,
            'test',
            ['1998.mohamad.yari@gmail.com']
        )
        form.send(fail_silently=False)
    return render(request, 'home/contact.html')

djangoProject/home/templates/home/change.html
{% extends 'admin/change_list.html' %}

{% block extrahead %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"
            integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css"
         integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w=="
         crossorigin="anonymous"
         referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <script>

    window.onload = function (){
        var ctx = document.getElementById('myChart');
        {% regroup cl.queryset|dictsort:'sell' by sell as sell_list %}
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for i in sell_list %}'{{ i.list|safe|cut:"Product:" }}',{% endfor %}],
        datasets: [{
            label: '# of Votes',
            data: [{% for i in sell_list %}'{{ i.grouper }}',{% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.8)',
                'rgba(54, 162, 235, 0.8)',
                'rgba(255, 206, 86, 0.8)',
                'rgba(75, 192, 192, 0.8)',
                'rgba(153, 102, 255, 0.8)',
                'rgba(255, 159, 64, 0.8)'
{#                {% for i in change %}'{{ i.color }}' {% endfor %}#}
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }

    }
 });
}


    </script>

{% endblock %}


{% block content %}
    <h3>Chart</h3>
    <canvas id="myChart" width="150" height="30"></canvas>
    {{ block.super }}
{% endblock %}

djangoProject/home/templates/home/contact.html
{% extends 'base.html' %}
{% block moha %}
    <div class="container">
        <div class="card bg-dark mt-5 p-5">
            <form method="post" action="{% url 'home:contact' %}">
            {% csrf_token %}
            <h1 class="text-center" style="color: goldenrod">contact form</h1>
            <div class="row mt-3">
                <div class="col-6">
                    <input type="text" name="subject" class="form-control" placeholder="subject">
                </div>
                <div class="col-6">
                    <input type="email" name="email" class="form-control" placeholder="email">
                </div>
            </div>
                <div class="row mt-3">
                    <textarea name="message" class="form-control" placeholder="message" rows="4"></textarea>
                </div>
                <button type="submit" class="btn btn-danger mt-3">send email</button>
            </form>
        </div>
    </div>
{% endblock %}

djangoProject/home/templates/home/detail.html
{% extends 'base.html'  %}
{% load jformat %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'home/css/test.css' %}">
{% endblock %}
{% block title %}detail{% endblock %}
{% block moha %}
   <div class="container">

     <h1>{{ product.name }}</h1>
   <h4>rate: {{ product.average }}</h4><br>
    <img style="width: 250px" src="{{ product.image.url }}" alt=""><br>
    <p>{{ product.information|safe }}</p>
   <div class="row">
       {% for img in images %}
           <img src="{{ img.image.url }}" style="width: 100px;height: 100px;" alt="">
       {% endfor %}
    {% if is_favourite %}
        <a href="{% url 'home:favourite' product.id %}"><i class="fa fa-heart" style="color: red; font-size: 24px;"></i></a>
        {% else %}
        <a href="{% url 'home:favourite' product.id %}"><i class="fa fa-heart-o" style="color: red; font-size: 24px;"></i></a>
   {% endif %}
   </div>
    <h2> like: {{ product.total_like }}</h2>
    {% if request.user.is_authenticated %}
            <a href="{% url 'home:product_like' product.id %}"
               class="btn btn-info {% if is_dislike %}disabled {% endif %}">like</a><br><br>
        <h2> dislike: {{ product.total_dislike }}</h2>
            <a href="{% url 'home:product_dislike' product.id %}"
               class="btn btn-primary {% if is_like %}disabled {% endif %}">dislike</a><br><br>
    {% endif %}
    {% if product.status == 'Both' %}
        <form action="" method="post">
              {% csrf_token %}
            {% for data in size %}
               <input type="radio" value="{{ data.id }}" {% if variants.id == data.id %} checked {% endif %}
                      name="select" onchange="this.form.submit();">
                <a href="" style="text-decoration: none">{{ data.size_variant }}</a>
        {% endfor %}
        </form><br>

            <form action="" method="post">
              {% csrf_token %}
            {% for data in colors %}
               <input type="radio" value="{{ data.id }}" {% if variants.id == data.id %} checked {% endif %}
                      name="select" onchange="this.form.submit();">
                <a href="" style="text-decoration: none">{{ data.color_variant }}</a>
                {% endfor %}
        </form><br>
    {% endif %}
   <div  class="card bg-danger m-2">
        {% if  variants.id %}
       <h4>price:{{ variants.total_price }}</h4>
            {% else %}
            <h4>price:{{ product.total_price }}</h4>
       {% endif %}

   </div>






   <div class="card">
       {% if product.status != 'None' %}
           <form method="post" action="{% url 'cart:add_cart' product.id %}">
           {% csrf_token %}
               <input type="hidden" name="select"  value="{{ variants.id }}">
               <input type="number" name="quantity" min="1" value="1" max="{{ variants.amount }}"
               required oninvalid="setCustomValidity('باید تعداد حداکثر{{ variants.amount }} باشد')">
            <button type="submit">Add</button>
       </form>
       {% else %}
            <form method="post" action="{% url 'cart:add_cart' product.id %}">
           {% csrf_token %}
                <input type="number" name="quantity" min="1" value="1" max="{{ product.amount }}"
                required oninvalid="setCustomValidity('باید تعداد حداکثر{{ product.amount }} باشد')">
            <button type="submit">Add</button>
       </form>
       {% endif %}

    </div>










    <hr>



          <div class="row comment">
              <div class="col-6">
                  {% if user.is_authenticated %}
                  <form method="post" action="{% url 'home:product_comment' product.id %}">
                      {% csrf_token %}
                      <div class="card">
                          <div class="row">
                              <div class="col-12">
                                  <div class="comment-box">
                                      <h4>Add Comment</h4>
                                      <div class="rating">
                                          <input type="radio" name="rate" value="5" id="5"> <label for="5">&star;</label>
                                          <input type="radio" name="rate" value="4" id="4"> <label for="4">&star;</label>
                                          <input type="radio" name="rate" value="3" id="3"> <label for="3">&star;</label>
                                          <input type="radio" name="rate" value="2" id="2"> <label for="2">&star;</label>
                                          <input type="radio" name="rate" value="1" id="1"> <label for="1">&star;</label>
                                      </div>
                                      <div class="comment-area">
                                          <textarea name="comment" class="form-control"
                                                    rows="4" required oninvalid="setCustomValidity('لطفا نظر خود را درج کنید')"></textarea>
                                      </div>
                                      <div class="text-center">
                                          <button type="submit" class="btn-danger">send comment</button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </form>
                  {% endif %}
              </div>
          </div>


            {% for com in comment %}
                <h2>Comment User</h2>
                <div class="card bg-dark text-white">
                    <div class="row ">
                        <div class="col-8">
                            <p>{{ com.user.username }}</p>
                        </div>
                            <div class="col-4">
                                <div class="comment-rating">
                                <i class="fa fa-star{% if com.rate < 1 %}-o empty{% endif %}"></i>
                                <i class="fa fa-star{% if com.rate < 2 %}-o empty{% endif %}"></i>
                                <i class="fa fa-star{% if com.rate < 3 %}-o empty{% endif %}"></i>
                                <i class="fa fa-star{% if com.rate < 4 %}-o empty{% endif %}"></i>
                                <i class="fa fa-star{% if com.rate < 5 %}-o empty{% endif %}"></i>

                                </div>
                        </div>
                </div>

                    <div class="row p-3">
                        <p>{{ com.comment }}</p>
                    </div>
                    <div class="row">
                        <div class="p-2 m-2">

                            {% if user.is_authenticated %}
                                <a href="{% url 'home:comment_like' com.id %}" class="like m-2 cursor">
                                <i class="fa fa-thumbs-o-up {% if is_comment_dislike %} disabled {% endif %}">
                                <span>like</span>&nbsp {{ com.total_comment_like }}
                                </i>
                                </a>
                            {% endif %}
                        </div>
                     <div class="row">
                        <div class="p-2 m-2">
                            {% if user.is_authenticated %}
                                <a href="{% url 'home:comment_dislike' com.id %}" class="dislike m-2 cursor">
                                <i class="fa fa-thumbs-o-down {% if is_comment_like %} disabled {% endif %}">
                                <span>dislike</span>&nbsp {{ com.total_comment_dislike }}
                                </i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    </div>
                    <form method="post" action="{% url 'home:product_reply' product.id com.id %}">
                        {% csrf_token %}
                        <textarea name="comment" id="comment" placeholder="reply..." class="form-control" rows="4" required oninvalid="setCustomValidity('لطفا نظر خود را درج کنید')" ></textarea>
                        <div class="mt-2">
                            <button type="submit" class="btn btn-info">send Reply</button>
                        </div>
                    </form>

                    {% for data in com.comment_reply.all %}
                        <div class="bg-danger text-white mt-2 p-2">
                        <p>{{ data.comment }}</p>
                        </div>
                    {% endfor %}
             </div>
                {#    {% for tag in  similar %}#}
{#        <a href="{% url 'home:detail' tag.id %}">#}
{#        <img style="width: 200px; height: 200px;" src="{{ tag.image.url }}" alt="">#}
{#        </a>#}
{#    {% endfor %}#}
            {% endfor %}


   {% block script %}
    {% if product.status != 'None' %}

         <script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for i in change %} {% if variants.id == i.variant_id %} '{{ i.update|jformat:"%A %d %B %Y" }}' {% endif %} ,{% endfor %}],
        datasets: [{
            label: '# of Votes',
            data: [{% for i in change %} {% if variants.id == i.variant_id %} {{ i.unit_price }} {% endif %} ,{% endfor %}],
            backgroundColor: [
                {#'rgba(255, 99, 132, 0.8)',#}
                {#'rgba(54, 162, 235, 0.8)',#}
                {#'rgba(255, 206, 86, 0.8)',#}
                {#'rgba(75, 192, 192, 0.8)',#}
                {#'rgba(153, 102, 255, 0.8)',#}
                {#'rgba(255, 159, 64, 0.8)'#}
                {% for i in change %}'{{ i.color }}' {% endfor %}
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
      options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }

    }
 });

</script>
       {% else %}



        <script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for i in update %} '{{ i.update|jformat:"%A %d %B %Y" }}' ,{% endfor %}],
        datasets: [{
            label: '# of Votes',
            data: [ {% for i in update %} {{ i.unit_price }} ,{% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 0.8)',
                'rgba(54, 162, 235, 0.8)',
                'rgba(255, 206, 86, 0.8)',
                'rgba(75, 192, 192, 0.8)',
                'rgba(153, 102, 255, 0.8)',
                'rgba(255, 159, 64, 0.8)'
{#                {% for i in change %}'{{ i.color }}' {% endfor %}#}
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
       options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }

    }
 });

</script>

   <div class="row">
       <canvas id="myChart" width="150" height="30"></canvas>
   </div>
   </div>

    {% endif %}
   {% endblock %}

       <br><br><br>



{% endblock %}

djangoProject/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}
{% block script %}
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block title %}
    home page
{% endblock %}
{% block moha %}
<h1> home page</h1>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
      {% for i in gallery %}
    <div class="carousel-item {% if forloop.first %} active {% endif %}">
      <img src="{{ i.image.url }}" style="width: auto;height: 400px;" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ i.name }}</h5>

      </div>
    </div>
      {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
    <br>
</div>
    <div class="container-fluid">
        <!-- Swiper -->
    <div class="swiper-container slider1">
      <div class="swiper-wrapper">
    {% for i in create %}

        <div class="swiper-slide">

        <div class="card" style="width: 23rem;">
            <a href="{% url 'home:detail' i.id %}">
          <img  src="{{ i.image.url }}" style="height: 250px" class="card-img-top" alt="...">
            </a>
          <div class="card-body">
            <h5 class="card-title">{{ i.name }}</h5>

        <a href="{% url 'home:detail' i.id %}" class="btn btn-primary">Go</a>


          </div>
            </div>
        </div>

       {% endfor %}
      </div>

      <div class="swiper-pagination"></div>
    </div>
    <!-- Swiper JS -->
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    </div>
{% endblock %}